export const options = {
    section: document.body,
    delay: .1,
    direction: 'vertical',
    speed: 1,
    touchSpeed: 1.5,
    jump: 110,
    touch: false,
    fixedClass: false,
    resize: true,
    preload:true,
    multFirefox: 15,
    scrollMax: 0,
    ticking: false,
    initFuncs: [],
}