export const options = {
    delay: .1,
    direction: 'vertical',
    speed: 1,
    delay: 0,
    touchSpeed: 1.5,
    jump: 110,
    callback: [],
    touch: false,
    fixedClass: false,
    resize: true,
    preload:true,
    parallax: false,
    multFirefox: 15,
    scrollMax: 0,
    ticking: false,
    initFuncs: [],
    scrollFuncs: {},
    preloadFuncs: {}
}